name: sf-workflow-flyway-test

# Controls when the action will run.
on:
  push:
    branches:
      - db-flyway2
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: db-flyway2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install Flyway
        run: |
          echo "Installing Flyway"
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.13.0/flyway-commandline-10.13.0-linux-x64.tar.gz | tar xvz
          export PATH="$PATH:$GITHUB_WORKSPACE/flyway-10.13.0"

      - name: List migrations directory for debugging
        run: |
          echo "Listing contents of migrations directory"
          ls -al $GITHUB_WORKSPACE/migrations

      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:snowflake://${{ secrets.SF_ACCOUNT }}.snowflakecomputing.com/?db=${{ secrets.SF_FLYWAY_DB }}&schema=${{ secrets.SF_SCHEMA_TEST }}
          FLYWAY_USER: ${{ secrets.SF_USERNAME }}
          FLYWAY_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "Running Flyway migrations"
          export JAVA_TOOL_OPTIONS="--add-opens=java.base/java.nio=ALL-UNNAMED"
          $GITHUB_WORKSPACE/flyway-10.13.0/flyway -locations=filesystem:$GITHUB_WORKSPACE/migrations migrate